/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudProvider : Cloud provider.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudProvider {
    /// Indicates the type of this object. Will be 'CloudProvider' link.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Unique identifier of the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the cloud provider for display purposes.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Human friendly identifier of the cloud provider, for example `aws`.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether the cloud provider is enabled for deploying an OSD cluster.
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl CloudProvider {
    /// Cloud provider.
    pub fn new(enabled: bool) -> CloudProvider {
        CloudProvider {
            kind: None,
            id: None,
            display_name: None,
            name: None,
            enabled,
        }
    }
}


