/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudRegion : Description of a region of a cloud provider.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudRegion {
    /// Indicates the type of this object. Will be 'CloudRegion'.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Unique identifier of the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the region for display purposes, for example `N. Virginia`.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether the region is enabled for deploying an OSD cluster.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// The Kafka instance types supported by this region.
    #[serde(rename = "supported_instance_types")]
    pub supported_instance_types: Vec<String>,
    /// Indicates whether there is capacity left per instance type
    #[serde(rename = "capacity")]
    pub capacity: Vec<crate::models::RegionCapacityListItem>,
}

impl CloudRegion {
    /// Description of a region of a cloud provider.
    pub fn new(enabled: bool, supported_instance_types: Vec<String>, capacity: Vec<crate::models::RegionCapacityListItem>) -> CloudRegion {
        CloudRegion {
            kind: None,
            id: None,
            display_name: None,
            enabled,
            supported_instance_types,
            capacity,
        }
    }
}


