/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorAllOf {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "operation_id", skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
}

impl ErrorAllOf {
    pub fn new() -> ErrorAllOf {
        ErrorAllOf {
            code: None,
            reason: None,
            operation_id: None,
        }
    }
}


