/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstantQuery {
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "value")]
    pub value: f64,
}

impl InstantQuery {
    pub fn new(value: f64) -> InstantQuery {
        InstantQuery {
            metric: None,
            timestamp: None,
            value,
        }
    }
}


