/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KafkaUpdateRequest {
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Whether connection reauthentication is enabled or not. If set to true, connection reauthentication on the Kafka instance will be required every 5 minutes.
    #[serde(rename = "reauthentication_enabled", skip_serializing_if = "Option::is_none")]
    pub reauthentication_enabled: Option<bool>,
}

impl KafkaUpdateRequest {
    pub fn new() -> KafkaUpdateRequest {
        KafkaUpdateRequest {
            owner: None,
            reauthentication_enabled: None,
        }
    }
}


