/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RangeQuery {
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<crate::models::Values>>,
}

impl RangeQuery {
    pub fn new() -> RangeQuery {
        RangeQuery {
            metric: None,
            values: None,
        }
    }
}


