/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RegionCapacityListItem : schema for a kafka instance type capacity in region



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RegionCapacityListItem {
    /// kafka instance type
    #[serde(rename = "instance_type", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<String>,
    /// flag indicating whether the capacity for the instance type in the region is reached
    #[serde(rename = "max_capacity_reached")]
    pub max_capacity_reached: bool,
}

impl RegionCapacityListItem {
    /// schema for a kafka instance type capacity in region
    pub fn new(max_capacity_reached: bool) -> RegionCapacityListItem {
        RegionCapacityListItem {
            instance_type: None,
            max_capacity_reached,
        }
    }
}


