/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServiceAccountRequest : Schema for the request to create a service account



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceAccountRequest {
    /// The name of the service account
    #[serde(rename = "name")]
    pub name: String,
    /// A description for the service account
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ServiceAccountRequest {
    /// Schema for the request to create a service account
    pub fn new(name: String) -> ServiceAccountRequest {
        ServiceAccountRequest {
            name,
            description: None,
        }
    }
}


