/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServiceStatus : Schema for the service status response body



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceStatus {
    #[serde(rename = "kafkas", skip_serializing_if = "Option::is_none")]
    pub kafkas: Option<Box<crate::models::ServiceStatusKafkas>>,
}

impl ServiceStatus {
    /// Schema for the service status response body
    pub fn new() -> ServiceStatus {
        ServiceStatus {
            kafkas: None,
        }
    }
}


