/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServiceStatusKafkas : The Kafka resource api status



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceStatusKafkas {
    /// Indicates whether we have reached Kafka maximum capacity
    #[serde(rename = "max_capacity_reached")]
    pub max_capacity_reached: bool,
}

impl ServiceStatusKafkas {
    /// The Kafka resource api status
    pub fn new(max_capacity_reached: bool) -> ServiceStatusKafkas {
        ServiceStatusKafkas {
            max_capacity_reached,
        }
    }
}


