/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VersionMetadataAllOf {
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<crate::models::ObjectReference>>,
}

impl VersionMetadataAllOf {
    pub fn new() -> VersionMetadataAllOf {
        VersionMetadataAllOf {
            collections: None,
        }
    }
}


