/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AclPermissionType {
    #[serde(rename = "ALLOW")]
    ALLOW,
    #[serde(rename = "DENY")]
    DENY,

}

impl ToString for AclPermissionType {
    fn to_string(&self) -> String {
        match self {
            Self::ALLOW => String::from("ALLOW"),
            Self::DENY => String::from("DENY"),
        }
    }
}

impl Default for AclPermissionType {
    fn default() -> AclPermissionType {
        Self::ALLOW
    }
}




