/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AclBinding : Represents a binding between a resource pattern and an access control entry



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AclBinding {
    #[serde(rename = "resourceType")]
    pub resource_type: crate::models::AclResourceType,
    #[serde(rename = "resourceName")]
    pub resource_name: String,
    #[serde(rename = "patternType")]
    pub pattern_type: crate::models::AclPatternType,
    /// Identifies the user or service account to which an ACL entry is bound. The literal prefix value of `User:` is required. May be used to specify all users with value `User:*`.
    #[serde(rename = "principal")]
    pub principal: String,
    #[serde(rename = "operation")]
    pub operation: crate::models::AclOperation,
    #[serde(rename = "permission")]
    pub permission: crate::models::AclPermissionType,
}

impl AclBinding {
    /// Represents a binding between a resource pattern and an access control entry
    pub fn new(resource_type: crate::models::AclResourceType, resource_name: String, pattern_type: crate::models::AclPatternType, principal: String, operation: crate::models::AclOperation, permission: crate::models::AclPermissionType) -> AclBinding {
        AclBinding {
            resource_type,
            resource_name,
            pattern_type,
            principal,
            operation,
            permission,
        }
    }
}


