/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AclBindingListPage : A page of ACL binding entries



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AclBindingListPage {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::AclBinding>>,
    /// Total number of entries in the full result set
    #[serde(rename = "total")]
    pub total: f32,
    /// Current page number (returned for fetch requests)
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// Number of entries per page (returned for fetch requests)
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f32>,
}

impl AclBindingListPage {
    /// A page of ACL binding entries
    pub fn new(total: f32) -> AclBindingListPage {
        AclBindingListPage {
            items: None,
            total,
            page: None,
            size: None,
        }
    }
}


