/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConfigEntry : Key value pair indicating possible configuration options for a topic.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigEntry {
    /// The key indicating what configuration entry you would like to set for the topic.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Value to indicate the setting on the topic configuration entry.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ConfigEntry {
    /// Key value pair indicating possible configuration options for a topic.
    pub fn new() -> ConfigEntry {
        ConfigEntry {
            key: None,
            value: None,
        }
    }
}


