/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NewTopicInput : Input object to create a new topic.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewTopicInput {
    /// The topic name, this value must be unique.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "settings")]
    pub settings: Box<crate::models::TopicSettings>,
}

impl NewTopicInput {
    /// Input object to create a new topic.
    pub fn new(name: String, settings: crate::models::TopicSettings) -> NewTopicInput {
        NewTopicInput {
            name,
            settings: Box::new(settings),
        }
    }
}


