/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Topic : Kafka Topic (A feed where records are stored and published)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Topic {
    /// The name of the topic.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Topic configuration entry.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<crate::models::ConfigEntry>>,
    /// Partitions for this topic.
    #[serde(rename = "partitions", skip_serializing_if = "Option::is_none")]
    pub partitions: Option<Vec<crate::models::Partition>>,
}

impl Topic {
    /// Kafka Topic (A feed where records are stored and published)
    pub fn new() -> Topic {
        Topic {
            name: None,
            config: None,
            partitions: None,
        }
    }
}


