/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TopicSettings : Kafka Topic (A feed where records are stored and published)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TopicSettings {
    /// Number of partitions for this topic.
    #[serde(rename = "numPartitions")]
    pub num_partitions: i32,
    /// Topic configuration entry.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<crate::models::ConfigEntry>>,
}

impl TopicSettings {
    /// Kafka Topic (A feed where records are stored and published)
    pub fn new(num_partitions: i32) -> TopicSettings {
        TopicSettings {
            num_partitions,
            config: None,
        }
    }
}


