/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TopicsList : A list of topics.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TopicsList {
    /// The page
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// number of entries per page
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// Offset of the topic list
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum of returned topics
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Total number of topics
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// List of topics
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::Topic>>,
}

impl TopicsList {
    /// A list of topics.
    pub fn new() -> TopicsList {
        TopicsList {
            page: None,
            size: None,
            offset: None,
            limit: None,
            total: None,
            items: None,
        }
    }
}


