/*
 * Kafka Admin REST API
 *
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateTopicInput : Kafka Topic (A feed where records are stored and published)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateTopicInput {
    /// Topic configuration entries.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<crate::models::ConfigEntry>>,
    /// Number of partitions (only increasing supported)
    #[serde(rename = "numPartitions", skip_serializing_if = "Option::is_none")]
    pub num_partitions: Option<i32>,
}

impl UpdateTopicInput {
    /// Kafka Topic (A feed where records are stored and published)
    pub fn new() -> UpdateTopicInput {
        UpdateTopicInput {
            config: None,
            num_partitions: None,
        }
    }
}


