/*
 * Service Registry Fleet Manager
 *
 * Managed Service Registry cloud.redhat.com API Management API that lets you create new registry instances. Registry is a datastore for standard event schemas and API designs. Service Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Registry is an Managed version of upstream project called Apicurio Registry. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.
 *
 * The version of the OpenAPI document: 0.0.6
 * Contact: rhosak-eval-support@redhat.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceStatus : Schema for the service status response body



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceStatus {
    /// Boolean property indicating if the maximum number of total instances have been reached, therefore creation of more instances should not be allowed.
    #[serde(rename = "max_instances_reached", skip_serializing_if = "Option::is_none")]
    pub max_instances_reached: Option<bool>,
}

impl ServiceStatus {
    /// Schema for the service status response body
    pub fn new() -> ServiceStatus {
        ServiceStatus {
            max_instances_reached: None,
        }
    }
}


